name: "Right Agent - Build"
on:
  push:
    branches:
      - master
      - "*_cow"
    tags:
      - release*

env:
  # HOME required by Setup Git and Setup Go Steps
  HOME: ${{ github.workspace }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      # SSH Agent Setup required for git to pull modules from private repos
      - name: SSH Agent Setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GLOBAL_FLEXERA_CI_PRIVATE_SSH_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GLOBAL_FLEXERA_CI_PRIVATE_SSH_KEY }}
          submodules: recursive

      - name: Before Install
        run: |
          sudo apt-get update
          sudo apt-get install -y libsasl2-dev libsqlite3-dev libxml2-dev libxslt-dev libmysqlclient-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'
          bundler-cache: true

      - name: Build
        run: |
          gem install bundler -v 2.2.32
          bundle config set cache_all true
          bundle exec rake ci:spec
